C++11 and cupla target linking in cmake
alpaka-group/cupla pull request #104
Opened 2019-04-16 13:55 UTC by tdd11235813

it seems there is a lot of redundancy in the cmake files, i.e., there are many internal variables and there are targets that do almost the same job with less code as they propagate the needed flags anyway. 

I would like to start to refactor in favor of using targets. This PR is just a start for that, also to initiate some feedback on potential issues.

This PR contains:
- C++11 feature on cupla target
- already includes the cupla link inside the `CUPLA_ADD_EXECUTABLE`
- examples rely on implicit cupla target linking, so you just have:
```cmake
cupla_add_executable(${PROJECT_NAME} ${_FILES_SOURCE_CXX})
target_include_directories(${PROJECT_NAME} PRIVATE "../common/")
```

Questions for next step:
- do you agree with these changes and this approach:
- I would like to modernize things in a separate PR, because I need this one only for #103 (and I also want to change the license before refactoring)
- may I use `macro()` instead of `function()` for `CUPLA_ADD_EXECUTABLE`? I do not see a need to create a separate scope for that (got issues with HIP and (un)scoped variables)
- I would like to bump the version from 0.1.1 to 0.1.2 in this PR

2019-04-29 08:47 UTC, ax3l commented
`I would like to bump the version from 0.1.1 to 0.1.2 in this PR` -> we bump versions only in releases so we can write a changelog, not in individual `dev` features

2019-04-29 08:49 UTC, ax3l approved these changes
LGTM so far

2019-05-06 10:04 UTC, tdd11235813 commented
ok, thanks for reviewing. Just included a commit for `CUDA_ADD_EXECUTABLE` to be a macro instead of a function, hope it is ok. If so, we can merge.

PS: 
> we bump versions only in releases so we can write a changelog, not in individual dev features

ok, no prob. For our benchmark I'll add the commit hash to address a code version.

2019-05-09 09:04 UTC, psychocoderHPC approved these changes

2019-05-09 09:11 UTC, psychocoderHPC requested changes
Discussed offline: we will remove the last commit which change the function `CUPLA_ADD_EXECUTABLE` to a macro because this is a BUG fix for HIP

2019-05-09 10:49 UTC, tdd11235813 commented
resetted to previous commit, already run successfully on travis => ready for merge

2019-05-09 13:30 UTC, psychocoderHPC approved these changes

2019-05-09 13:33 UTC, tdd11235813 commented
was the last commit "Merge branch 'dev' into dev-targets" intended? Just see a blank line added. For upstream update I could do a rebase instead.

2019-05-10 11:54 UTC, psychocoderHPC commented
I rebased it now. The merge PR was from online merging but the gui is not showing very well the changes, therefore, I added by accident a while line.

2019-05-13 12:45 UTC, ax3l commented
@psychocoderHPC ready for merge?

2019-05-13 14:08 UTC, tdd11235813 commented
I gonna squash some commits, keeping the style changes in a separate one.
(some commits are not working standalone due to missing code line)

2019-05-20 13:42 UTC, merged