fix atomic function return type
alpaka-group/cupla pull request #163
Opened 2020-03-16 16:09 UTC by psychocoderHPC

Change return type from void to argument type.

Bug was introduced with #161

2020-03-16 16:58 UTC, sbastrakov requested changes
In case the return type is not `void`, I guess `return` is missing in all these functions?

2020-03-17 09:44 UTC, psychocoderHPC commented
Yes ohh I looked to it and thought do not forget to add the return^^

2020-03-17 09:47 UTC, psychocoderHPC commented
fixed

2020-03-17 10:04 UTC, sbastrakov approved these changes

2020-03-17 10:05 UTC, merged