Update to clang format 12.0.1
alpaka-group/cupla pull request #220
Opened 2021-11-01 14:32 UTC by SimeonEhrig

2021-11-02 09:22 UTC, psychocoderHPC requested changes

2021-11-02 09:22 UTC, psychocoderHPC commented on .clang-format
> -IncludeCategories:
Do not remove the include.

2021-11-02 14:55 UTC, SimeonEhrig commented
@psychocoderHPC Can you please review again.

2021-11-02 14:59 UTC, bernhardmgruber approved these changes

2021-11-09 14:32 UTC, psychocoderHPC approved these changes

2021-11-09 14:32 UTC, merged