fix missing include
alpaka-group/cupla pull request #226
Opened 2022-05-09 08:35 UTC by psychocoderHPC

fix https://github.com/ComputationalRadiationPhysics/spack-repo/pull/17

Missing inlcude to all meth functions.

2022-05-09 10:05 UTC, sbastrakov approved these changes

2022-05-09 10:07 UTC, sbastrakov requested changes
The change is fine.

However, in the commit message you linked to the wrong PR. Also you had 2 typos there. I fixed both PR and typos in edited PR message.

2022-05-10 06:04 UTC, psychocoderHPC commented
I fixed the commit message.

2022-05-10 06:17 UTC, sbastrakov approved these changes

2022-05-10 08:02 UTC, merged